apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-ewgh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-15-tenant/load-app-af47f40b-a853-4d8d-bdb5-6bbd64d303b4/devfile-sample-java-springboot-basic-ewgh@sha256:b2eaf8461d78c1e1b4ab074924ec98749e15626379432b21dd95ae95e179bdbe
        name: my-java-springboot
        resources: {}
status: {}
